### ISSUE TITLE
segmentation fault in word2vec

### ISSUE THREAD

**Issue by j07nikita** [tmikolov/word2vec#44]
$ gcc word2vec.c -pthread -lm -g
$ ./a.out -train text8 -output vectors.bin -cbow 1 -size 200 -window 8 -negative 25 -hs 0 -sample 1e-4 -threads 20 -binary 1 -iter 15
Starting training using file text8
Vocab size: 71291
Words in train file: 16718843
Segmentation fault (core dumped)

**Comment by j07nikita** [comment]
solved.

**Comment by kokeman** [comment]
> solved.

How did you solve it?
